.Dd $Mdocdate$
.Dt ENUMDATE 1
.Os
.Sh NAME
.Nm enumdate
.Nd Enumerate dates between two dates
.Sh SYNOPSIS
.Nm
.Ar yyyymmdd1
.Ar yyyymmdd2
.Sh DESCRIPTION
The
.Nm
outputs every date in given range of dates
.Pq inclusive
to standard output, line by line.
Year
.Ar yyyy
can be in 1 to 4 digits.
.Sh EXIT STATUS
.Ex -std
