.Dd August  2, 2024
.Dt MIME-MAKE 1
.Os
.Sh NAME
.Nm mime-make
.Nd Generate MIME Multipart Formatted Data
.Sh SYNOPSIS
.Nm
.Op options
.Ar input-group ...
.Nm
.Fl m | -generatemimeboundary
.Sh DESCRIPTION
In first form, generate MIME Multipart Formatted Data
consists of given
.Ar input-group Ns s
for HTTP form-data or mail body or mail attachment.
In second form, generate a MIME boudary.
.Pp
The
.Op options
are as follows:
.Bl -tag -width Ds
.It Fl -bo , Fl -wh
Output body only or with header
.Pq Content-Type
respectively
.Pq default: Fl -bo .
.It Fl b Ar boundary
Specify custom MIME boundary.
.It Fl -crlf , Fl -lf
Specify end-of-line representation
.Po
default:
.Fl -lf
for HTTP,
.Fl -crlf
for mail
.Pc
.It Fl -b64 , Fl -raw
Output in
.Xr base64 1
format or raw format respectively
.Pq default: Fl -raw .
Works for HTTP only; the mail output
is always encoded by
.Xr base64 1 .
.El
.Pp
The
.Ar input-group Ns s
are as follows, and must be consistent:
.Bl -tag -width Ds
.It Fl T Ar name Ar value , Fl Tf Ar name Ar file
Specify textform.
.It Fl F Ns Oo Cm t Oc Ns Oo Cm f Oc Ar name Oo Ar filetype Oc Oo Ar filename Oc Ar file
Specify fileform.
With
.Cm t ,
specify
.Ar filetype .
With
.Cm f ,
specify
.Ar filename .
.It Fl M Ar file
Specify mail body.
.It Fl A Ns Oo Cm t Oc Ns Oo Cm f Oc Oo Ar filetype Oc Oo Ar filename Oc Ar file
Specify mail attachment.
With
.Cm t ,
specify
.Ar filetype .
With
.Cm f ,
specify
.Ar filename .
.El
.Sh EXIT STATUS
.Ex -std
